baseURL = 'https://ololiuhqui.github.io/ervakambo/'
languageCode = ''
title = 'Erva Kambo'
defaultContentLanguage = 'en'
copyright = 'Made by Ludovico Caluori - 2024'
enableRobotsTXT = true



[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"
      [[module.mounts]]
      source = 'assets'
      target = 'assets'