baseURL = 'https://ervakambo.com'
languageCode = ''
title = 'Erva Kambo'
defaultContentLanguage = 'it'
defaultContentLanguageInSubDir = true
copyright = 'Made by Ludovico Caluori - 2024'
enableRobotsTXT = true


[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"
      [[module.mounts]]
      source = 'assets'
      target = 'assets'