baseURL = 'https://ervakambo.com'
languageCode = ''
title = 'Erva Kambo'
defaultContentLanguage = 'it'
defaultContentLanguageInSubDir = true
copyright = "© 2026 all rights reserved - Designed by Ludovico Caluori 🎨 "
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"] # This disables categories and tags and removes them from sitemap
googleAnalytics = "G-VS40WF4TQM"

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"
      [[module.mounts]]
      source = 'assets'
      target = 'assets'