# contentDir = 'content/en'
disabled = false
languageCode = 'it-IT'
languageName = 'Italian'
title = 'Erva Kambo' # This will go in the Header as well
copyright = "© 2024 all rights reserved - Designed by Ludovico Caluori 🎨"
contentDir = "content/it"

# Change single params to false to remove from rendering
[params]
  subtitle = "Psicologa" # This goes in the header and in the site title

  # PAGES
  [params.homepage]
    preTitle = 'Psicologa a Firenze'
    title = "Erva Kambo"
    intro= """Mi piace aiutare le persone a sentirsi comprese, ad affrontare i propri dolori e le proprie gioie, e
        ritrovare la forza interiore nei momenti difficili della loro vita. Attraverso una relazione basata sulla
        fiducia e l’empatia, sarà possibile dare vita ad uno spazio sicuro e accogliente in cui avrai
        l’opportunità di esplorare profondamente te stesso e sviluppare una maggiore **consapevolezza delle
        tue emozioni, pensieri e comportamenti**. Insieme esploreremo le difficoltà in ambito relazionale,
        familiare, lavorativo, di coppia, culturale e di genere. La tua **crescita personale** è la mia priorità e
        sono qui per accompagnarti in ogni fase del tuo percorso verso il tuo **benessere emotivo**.
        """
    mainButton = "Contattami"
    mainButtonRef = "https://wa.me/393801783513"
    [params.homepage.description]
    enabled = true
    # You can use some markdown safely for the description as long as you don't include line breaks
    secondTitle = ""
    paragraph = """"""
    paragraph2= "Colloqui svolti in italiano, inglese e albanese!"


[params.office]
 title = "Lo Studio"
 description = "Troverai un ufficio accogliente nel centro della bellissima città di Firenze."
 buttonText = "Indicazioni" 
 buttonLink = "https://maps.app.goo.gl/fxmD9cQXUVS5Xp9t8" # google maps share link here (for button)
 mapLink = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d23046.70708393103!2d11.250820486945312!3d43.77621354501747!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132a54126faf8b3d%3A0x37e724bfc089c27a!2sVia%20dei%20della%20Robbia%2C%2023%2C%2050132%20Firenze%20FI!5e0!3m2!1sit!2sit!4v1714143516043!5m2!1sit!2sit" # google maps embed link here

[params.contacts]
  title = "Invia la tua richiesta!"
  formCallToAction = ""
  socialCallToAction = "Contattami sulle piattaforme social qui sotto. Sentiti libero di scrivermi su Whatsapp!"
  [params.contacts.form]
    firstname = "Nome*"
    lastname = "Cognome*"
    email = "E-mail*"
    phone = "Numero di telefono*"
    Inquiry = "Richiesta*"
    checkbox = "Trattamento dei dati ai sensi di legge*"
    submitBtn = "Invia"

[params.services]
  title = "Consulenza"
  description = """Offro sostegno e consulenza psicologica individuale e di coppia. Con il mio approccio di
orientamento Cognitivo Comportamentale mi dedico alla mente, al corpo e alle pratiche del
benessere. Le nostre sessioni dureranno 60min in presenza oppure online. Insieme lavoreremo sulle
seguenti aree:"""
  [params.services.list]
    # You can add as much params.services.list.N as you like
    [params.services.list.0]
      title= "Promozione del benessere e dell’autostima"
      description= ""
    [params.services.list.01]
      title = "Crescita personale e la scoperta di sé"
      description= ""
    [params.services.list.02]
      title = "Migliorare le relazioni e le capacità comunicative"
      description= ""
    [params.services.list.03]
      title = "Difficoltà legate all’ansia e alla depressione"
      description= ""
    [params.services.list.04]
      title = "Difficoltà comportamentali"
      description= ""
    [params.services.list.05]
      title = "Dipendenza affettiva"
      description= ""
    [params.services.list.06]
      title = "Gestione dello stress e costruzione della resilienza"
      description= ""
    [params.services.list.07]
      title = "Migliorare le prestazioni e raggiungere gli obiettivi"
      description= ""
    [params.services.list.08]
      title = "Elaborazione del lutto e dei traumi"
      description= ""
    [params.services.list.09]
      title = "Gestione dei conflitti e crisi personali"
      description= ""
    [params.services.list.10]
      title = "Espatrio e vita all’estero"
      description= ""
  
# /. PAGES

[params.socials]
  enabled = true # enables/disables the whole social section
  callToAction= "Entra in contatto con me sui canali social >"
      [[params.socials.link]]
        name = "instagram"
        link = "https://www.instagram.com/ervakambo/"
      [[params.socials.link]]
        name = "linkedin"
        link = "https://www.linkedin.com/in/ervakambo/"
      [[params.socials.link]]
        name = "whatsapp"
        link = "https://wa.me/393801783513"
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.schedules]
  enabledFooter = false # This will add the schedules on the footer too
  enabledContacts = true # This will add the schedule to the contact page
  title = "Orari di apertura" # For contacts page only
  [params.schedules.days]
  # Use something like "Monday: 9-13" for each day
  # if left empty it is disabled (default)
    day1 = "Lunedì: 9:00 – 19:00"
    day2 = "Martedì: 9:00 – 19:00"
    day3 = "Mercoledì: 9:00 – 19:00"
    day4 = "Giovedì: 9:00 – 19:00"
    day5 = "Venerdì: 9:00 – 19:00"
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription = "Ordine degli Psicologi della Toscana N. 10278"
  vat = "P.IVA 07339790482"
  [params.footer.navigate]
  heading = "Naviga"   
  [params.footer.contacts]
  enabled = true # enables/disables the whole contacts section
  heading = "Contatti"
  address = "Viale Francesco Redi 127, Firenze"
  mail = "psicologa.kambo@gmail.com"
  mail2 = "erva.kambo@psypec.it"
  phone = "+39 3801783513"

[params.notfound]
  title = "404, pagina non trovata" # text for 404 page
 
[menus]
# If you add a new language remember to change the pageRef to match the desired content folder!
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Consulenza"
  pageRef = "/services"
  weight = 2
  [[menus.main]]
  name = "Lo Studio"
  pageRef = "/office"
  weight = 3
  [[menus.main]]
  name = "Contatti"
  pageRef = "/contacts"
  weight = 4