# contentDir = 'content/en'
disabled = false
languageCode = 'sq-AL'
languageName = 'Albanian'
title = 'Erva Kambo' # This will go in the Header as well
contentDir = "content/sq"

# Change single params to false to remove from rendering
[params]
  subtitle = "Psikologe" # This goes in the header and in the site title

  # PAGES
  [params.homepage]
    preTitle = 'Psikologe në Firence'
    title = "Erva Kambo"
    intro= """Të duhet të luftosh për të qënë vetvetja në një shoqëri që ndihet sikur nuk është menduar për ty? A
    ke vështirësi për të kuptuar ose emërtuar ndjenjat, nevojat dhe dëshirat e tua? Ndoshta ndihesh i
    padëgjuar, i padukshëm ose ndihesh sikur duhet të fshehësh disa pjesë të vehtes në mënyrë që të
    pranohesh nga të tjerët? Është e vështirë të ndihesh mirë kur ndihesh i zbrazur dhe i mbingarkuar.
    **Stresi, trauma** dhe **humbja e një personi të dashur** mund të ta vështirësojnë jetën e përditshme
    dhe në të njëjtën kohë të të sfidojnë me probleme si **ankthi e depresioni**.
    Terapia është ura që lidh betejat tona individuale me kujdesin ndaj vehtes dhe të tjerëve. Mbajtja e
    marrëdhënieve, arritja e qëllimeve madje dhe përjetimi i gëzimit, shpesh mund të ndihen si një
    betejë e vështirë në një botë shtypëse, dhe pesha e shtypjes mund të na izolojë nga vetja dhe të
    tjerët. Pavarësisht sfidave që jeta të ka sjellë kohët e fundit, nuk ke pse të mbetesh këtu. Vetëm ti
    mund të kurosh të gjitha pjesët e tua dhe të rifitosh ndjenjën e tërësisë dhe të dinjitetit. Nuk je
    vetëm!
        """
    mainButton = "Kontakto"
    mainButtonRef = "https://wa.me/393801783513"
    [params.homepage.description]
    enabled = true
    # You can use some markdown safely for the description as long as you don't include line breaks
    secondTitle = "Njihuni me Erva Kambo, Psikologe"
    paragraph = """Më pëlqen ti ndihmoj njerëzit të ndihen të kuptuar, të përballen me dhimbjen dhe gëzimin, dhe të
    gjejnë forcë të brëndshme në momente të vështira të jetës së tyre. Nëpërmjet një marrëdhënieje të
    bazuar në besim dhe ndjeshmëri, do të jetë e mundur të krijojmë një hapësirë të sigurt në të cilën do
    të kesh mundësinë të zbulosh thellësisht vehten dhe të zhvillosh një ndërgjegjësim më të madh
    për emocionet, mendimet dhe sjelljet e tua. Bashkë do të eksplorojmë çështje dhe probleme që
    lidhen me familjen, punën, identitetin, gjininë dhe kulturën. Unë mund të të ndihmoj të lëvizësh
    drejt një versioni të jetës tënde ku shqetësimi emocional dhe fizik nuk diktojnë më vendimet e tua.
    Bashkohu me mua në një proces zbulimi dhe rritjeje!"""
    paragraph2= "Ofroj shërbime në italisht, anglisht dhe shqip!"

[params.office]
 title = "Zyra"
 description = "Do të gjeni një zyrë mikpritëse në qendër të Firence."
 buttonText = "Udhëzime" 
 buttonLink = "https://maps.app.goo.gl/Vr4NJT2UjEoRnr5B8" # google maps share link here (for button)
 mapLink = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2880.2347138446667!2d11.229217612345396!3d43.78874244353238!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132a56bfd81a4af9%3A0x8557c053da3c550e!2sViale%20Francesco%20Redi%2C%20127%2C%2050144%20Firenze%20FI!5e0!3m2!1sit!2sit!4v1720106026343!5m2!1sit!2sit" # google maps embed link here
[params.contacts]
  title = "Rezervoni një takim tani!"
  formCallToAction = ""
  socialCallToAction = "Më kontaktoni në rrjetet sociale më poshtë. Mos ngurroni të më shkruani në Whatsapp!"
  [params.contacts.form]
    firstname = "Emri*"
    lastname = "Mbiemri*"
    email = "E-mail*"
    phone = "Telefon*"
    Inquiry = "Kërkesa juaj*"
    checkbox = "Kam lexuar dhe pranoj"
    submitBtn = "DËRGO"

[params.services]
  title = "Shërbimet"
  description = """ Ofroj mbështetje psikologjike dhe këshillim individual dhe në çift. Me qasjen time të
orientimit konjitiv - sjellës i përkushtohem mendjes, ndjenjave dhe praktikave të mirëqenies.
Seancat tona do të zgjasin 60 minuta personalisht ose online. Së bashku do mund të punojmë në fushat e mëposhtme:"""
  [params.services.list]
    # You can add as much params.services.list.N as you like
    [params.services.list.0]
      title= "Promovimi i mirëqënies dhe i vetëvlerësimit"
      description= ""
    [params.services.list.01]
      title = "Rritja personale dhe vetë-zbulimi"
      description= ""
    [params.services.list.02]
      title = "Përmirësimi i marrëdhënieve dhe i aftësive të komunikimit"
      description= ""
    [params.services.list.03]
      title = "Ankth dhe depresion"
      description= ""
    [params.services.list.04]
      title = "Vështirësi në sjellje"
      description= ""
    [params.services.list.05]
      title = "Varësia emocionale"
      description= ""
    [params.services.list.06]
      title = "Ndërtimi i qëndrueshmërisë"
      description= ""
    [params.services.list.07]
      title = "Përmirësimi i performancës dhe arritja e qëllimeve"
      description= ""
    [params.services.list.08]
      title = "Përpunimi i humbjes dhe përballja me traumën"
      description= ""
    [params.services.list.09]
      title = "Menaxhimi i stresit dhe krizat personale"
      description= ""
    [params.services.list.10]
      title = "Mërgimi dhe jeta jashtë shtetit"
      description= ""
  
# /. PAGES

[params.socials]
  enabled = true # enables/disables the whole social section
  callToAction= "Lidhu me mua në rrjetet sociale >"
      [[params.socials.link]]
        name = "instagram"
        link = "https://www.instagram.com/ervakambo/"
      [[params.socials.link]]
        name = "linkedin"
        link = "https://www.linkedin.com/in/ervakambo/"
      [[params.socials.link]]
        name = "whatsapp"
        link = "https://wa.me/393801783513"
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.schedules]
  enabledFooter = false # This will add the schedules on the footer too
  enabledContacts = true
  title = "Oraret" # For contacts page only
  [params.schedules.days]
  # Use something like "Monday: 9-13" for each day
  # if left empty it is disabled (default)
    day1 = "E Hënë: 9:00 - 18:00"
    day2 = "E Martë: 9:00 - 18:00"
    day3 = "E Mërkurë: 9:00 - 18:00"
    day4 = "E Enjte: 9:00 - 18:00"
    day5 = "E Premte: 9:00 - 18:00"
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription = "Urdhri i Psikologëve të Toskanës Nr. 10278"
  vat = "TVSH 07339790482"
  [params.footer.navigate]
  heading = "Navigoni"   
  [params.footer.contacts]
  enabled = true # enables/disables the whole contacts section
  heading = "kontakt"
  address = "Viale Francesco Redi 127, Firenze"
  mail = "psicologa@studiokambo.com"
  mail2 = "erva.kambo@psypec.it"
  phone = "+39 3801783513"

[params.notfound]
  title = "404, page not found" # text for 404 page
  
 
[menus]
# If you add a new language remember to change the pageRef to match the desired content folder!
  [[menus.main]]
  name = "Kryefaqja"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Shërbimet"
  pageRef = "/services"
  weight = 2
  [[menus.main]]
  name = "Zyra"
  pageRef = "/office"
  weight = 3
  [[menus.main]]
  name = "Kontaktet"
  pageRef = "/contacts"
  weight = 4